import useBodyScroll from "@/app/hooks/useBodyScroll";
import { AnimatePresence, motion } from "framer-motion";
import { useEffect, useMemo } from "react";
import { OrbitProgress } from "react-loading-indicators";

interface LoadingOverlayProps {
    show: boolean;
}

const tips = [
    "Tip: Regular practice helps you retain grammar rules longer.",
    "Tip: Try reading English articles to see grammar in context.",
    "Focusing on phonetics will significantly improve your accent.",
    "Did you know? Consistent short sessions are better than long rare ones.",
    "Don't worry about making mistakes; they are part of the learning process!",
    "Tip: Listen to English podcasts to improve your listening skills.",
    "Try explaining a grammar rule to someone else to reinforce it.",
    "Tip: Use flashcards to memorize new vocabulary efficiently.",
    "Watch movies with English subtitles to connect sounds with words.",
    "Tip: Write a daily journal in English to practice sentence structure.",
    "Record yourself speaking and listen back to identify areas for improvement.",
    "Tip: Learn phrases rather than individual words to sound more natural.",
    "Set your phone's language to English for constant immersion.",
    "Tip: Use mnemonics to remember tricky spelling rules.",
    "Read aloud to build muscle memory in your jaw and tongue.",
    "Tip: Join an English conversation club to practice speaking with others.",
    "Don't translate in your head; try to think directly in English.",
    "Tip: Label objects around your house with their English names.",
    "Focus on high-frequency words first to build a solid foundation.",
    "Tip: Use language learning apps for quick practice during breaks.",
    "Listen to English music and try to transcribe the lyrics.",
    "Tip: Pay attention to word stress; it can change the meaning of a word.",
    "Read children's books to master basic sentence patterns.",
    "Tip: Use a dictionary that provides example sentences.",
    "Practice tongue twisters to improve your clarity and speed.",
    "Tip: Follow English-speaking influencers on social media.",
    "Don't be afraid to ask for clarification if you don't understand.",
    "Tip: Use 'shadowing'—repeat what a native speaker says immediately after.",
    "Celebrate small wins, like understanding a joke or a song lyric.",
    "Tip: Learn the most common English idioms to sound like a local.",
    "Keep a dedicated notebook for new words and expressions.",
    "Tip: Practice verb conjugations until they become second nature.",
    "Read the news in English to stay informed and learn formal vocabulary.",
    "Tip: Engage in 'self-talk'—narrate your day in English as you go.",
    "Use a browser extension to translate words on the fly while browsing.",
    "Tip: Focus on the sounds that don't exist in your native language.",
    "Try writing short stories or poems to get creative with the language.",
    "Tip: Use online forums like Reddit to discuss your hobbies in English.",
    "Don't rush; quality of understanding is better than quantity of words.",
    "Tip: Pay attention to prepositions; they are often the trickiest part.",
    "Learn the International Phonetic Alphabet (IPA) for better pronunciation.",
    "Tip: Use sticky notes for grammar rules you find difficult.",
    "Find a language partner for a regular exchange of conversation.",
    "Tip: Listen to different English accents to improve your versatility.",
    "Use 'context clues' to guess the meaning of words you don't know.",
    "Tip: Practice your writing by commenting on English YouTube videos.",
    "Make sure to review what you learned yesterday before starting today.",
    "Tip: Use a thesaurus to find synonyms and expand your vocabulary.",
    "Don't get discouraged by plateaus; they are a sign of progress.",
    "Tip: Learn how to use transition words for smoother writing.",
    "Watch English cartoons; they use simple language and clear diction.",
    "Tip: Pay attention to the 'schwa' sound—it's the most common in English.",
    "Try translating your favorite song into English.",
    "Tip: Use 'spaced repetition' systems like Anki for long-term memory.",
    "Learn the difference between formal and informal English.",
    "Tip: Focus on the flow of the sentence, not just individual words.",
    "Don't be afraid to use simple sentences at first.",
    "Tip: Practice English while doing chores or commuting.",
    "Use a grammar checker, but try to understand why it's correcting you.",
    "Tip: Learn the names of common emotions to better express yourself.",
    "Read blogs about topics you are passionate about.",
    "Tip: Focus on 'minimal pairs' to distinguish similar sounds.",
    "Try to use a new word in three different sentences today.",
    "Tip: Learn the prefixes and suffixes to decode new words.",
    "Don't compare your progress to others; everyone learns at their own pace.",
    "Tip: Practice giving a 2-minute speech on a random topic.",
    "Use English-language recipes while cooking.",
    "Tip: Learn how to use modal verbs to express possibility and necessity.",
    "Watch TED talks to learn about diverse topics and formal speaking.",
    "Tip: Don't ignore punctuation; it changes the rhythm of your writing.",
    "Try thinking about your dreams in English.",
    "Tip: Use 'cloze' exercises to test your grammar and vocabulary.",
    "Learn common phrasal verbs—they are essential for natural speech.",
    "Tip: Focus on the melody and intonation of English sentences.",
    "Read product reviews in English before buying something.",
    "Tip: Practice your listening with English audiobooks.",
    "Don't overthink grammar while speaking; focus on communication.",
    "Tip: Learn the names of common household items and tools.",
    "Use English-language maps and navigation while traveling.",
    "Tip: Practice your pronunciation by recording yourself and comparing.",
    "Read English comics or graphic novels for visual context.",
    "Tip: Learn the difference between 'British' and 'American' English.",
    "Try writing a review for a movie you just watched.",
    "Tip: Use English-language puzzles and games to keep it fun.",
    "Don't be afraid to slow down your speech for better clarity.",
    "Tip: Learn the nuances of 'connotation'—the feeling behind a word.",
    "Use English for your to-do lists and calendar reminders.",
    "Tip: Practice your English by teaching a friend what you learned.",
    "Watch English interviews to see how people naturally converse.",
    "Tip: Learn how to use 'collocations'—words that naturally go together.",
    "Read the lyrics while listening to English music.",
    "Tip: Use English in your social media posts and captions.",
    "Don't let a bad day stop your learning; just do 5 minutes.",
    "Tip: Learn the names of common professions and their duties.",
    "Use English-language weather apps and news sites.",
    "Tip: Practice your listening by watching English documentaries.",
    "Learn the difference between 'active' and 'passive' voice.",
    "Tip: Use English-language educational platforms like Coursera.",
    "Don't be afraid to use gestures to help convey your meaning.",
    "Tip: Learn how to use 'relative clauses' for more complex sentences.",
    "Read English poetry to appreciate the rhythm of the language.",
    "Tip: Use English-language forums for your professional development.",
    "Practice your English by writing emails to yourself.",
    "Tip: Learn the names of common animals and their habitats.",
    "Use English-language search engines for your queries.",
    "Tip: Practice your listening by tuning into English radio stations.",
    "Don't forget to practice your spelling regularly.",
    "Tip: Learn how to use 'conditionals' to talk about hypothetical situations.",
    "Read English biographies to learn about interesting people.",
    "Tip: Use English-language apps for meditation and mindfulness.",
    "Practice your English by narrating what you see out the window.",
    "Tip: Learn the names of common plants and flowers.",
    "Use English-language shopping sites to learn product descriptions.",
    "Tip: Practice your listening by watching English vlogs.",
    "Don't be afraid to ask for help from native speakers.",
    "Tip: Learn how to use 'reported speech' for storytelling.",
    "Read English travel guides to learn about new places.",
    "Tip: Use English-language fitness apps and workout videos.",
    "Practice your English by describing your favorite hobby.",
    "Tip: Learn the names of common body parts and health terms.",
    "Use English-language cooking videos to learn new recipes.",
    "Tip: Practice your listening by watching English news broadcasts.",
    "Don't get hung up on perfection; aim for progress.",
    "Tip: Learn how to use 'conjunctions' to connect your ideas.",
    "Read English magazines to stay current with trends.",
    "Tip: Use English-language productivity tools and apps.",
    "Practice your English by writing a letter to your future self.",
    "Tip: Learn the names of common shapes and mathematical terms.",
    "Use English-language online games to chat with other players.",
    "Tip: Practice your listening by watching English movie trailers.",
    "Don't be afraid to experiment with the language.",
    "Tip: Learn how to use 'intensifiers' to add emphasis.",
    "Read English science articles to learn technical vocabulary.",
    "Tip: Use English-language apps for brain training and puzzles.",
    "Practice your English by describing your favorite childhood memory.",
    "Tip: Learn the names of common sports and their equipment.",
    "Use English-language fashion blogs to learn style vocabulary.",
    "Tip: Practice your listening by watching English comedy specials.",
    "Don't give up; every bit of practice counts.",
    "Tip: Learn how to use 'comparatives' and 'superlatives'.",
    "Read English history books to learn about the past.",
    "Tip: Use English-language apps for learning other skills.",
    "Practice your English by writing a summary of a book you read.",
    "Tip: Learn the names of common musical instruments.",
    "Use English-language photography blogs to learn art terms.",
    "Tip: Practice your listening by watching English talk shows.",
    "Don't be afraid to make a fool of yourself; it's part of learning.",
    "Tip: Learn how to use 'modal verbs of deduction'.",
    "Read English business articles to learn professional terms.",
    "Tip: Use English-language apps for budgeting and finance.",
    "Practice your English by describing your dream job.",
    "Tip: Learn the names of common celestial bodies and space terms.",
    "Use English-language tech blogs to learn about gadgets.",
    "Tip: Practice your listening by watching English reality shows.",
    "Don't be afraid to use a dictionary; it's a helpful tool.",
    "Tip: Learn how to use 'quantifiers' like some, any, many, much.",
    "Read English short stories to improve your narrative skills.",
    "Tip: Use English-language apps for gardening and nature.",
    "Practice your English by describing your favorite meal.",
    "Tip: Learn the names of common weather phenomena.",
    "Use English-language design blogs to learn creative terms.",
    "Tip: Practice your listening by watching English animated films.",
    "Don't be afraid to ask 'Why?' when learning a new rule.",
    "Tip: Learn how to use 'question tags' to confirm information.",
    "Read English mystery novels to keep yourself engaged.",
    "Tip: Use English-language apps for travel and navigation.",
    "Practice your English by writing a review for a restaurant.",
    "Tip: Learn the names of common architectural styles.",
    "Use English-language art blogs to learn aesthetic terms.",
    "Tip: Practice your listening by watching English sitcoms.",
    "Don't be afraid to use English in real-life situations.",
    "Tip: Learn how to use 'gerunds' and 'infinitives' correctly.",
    "Read English fantasy novels to expand your imagination.",
    "Tip: Use English-language apps for music and audio.",
    "Practice your English by describing your daily routine.",
    "Tip: Learn the names of common geological features.",
    "Use English-language history blogs to learn about events.",
    "Tip: Practice your listening by watching English debate videos.",
    "Don't be afraid to take breaks when you feel overwhelmed.",
    "Tip: Learn how to use 'linking verbs' to describe states.",
    "Read English self-help books for personal growth and language.",
    "Tip: Use English-language apps for health and wellness.",
    "Practice your English by writing a letter of recommendation.",
    "Tip: Learn the names of common psychological terms.",
    "Use English-language nature blogs to learn about wildlife.",
    "Tip: Practice your listening by watching English sports commentary.",
    "Don't be afraid to challenge yourself with harder materials.",
    "Tip: Learn how to use 'causative verbs' like have and get.",
    "Read English classic literature to see the language's evolution.",
    "Tip: Use English-language apps for coding and programming.",
    "Practice your English by describing your favorite place.",
    "Tip: Learn the names of common philosophical concepts.",
    "Use English-language science blogs to learn about discoveries.",
    "Tip: Practice your listening by watching English award shows.",
    "Don't be afraid to use English idioms, even if you're unsure.",
    "Tip: Learn how to use 'subjunctive mood' for hypothetical wishes.",
    "Read English non-fiction to learn about real-world topics.",
    "Tip: Use English-language apps for DIY and home improvement.",
    "Practice your English by writing a travel itinerary.",
    "Tip: Learn the names of common legal terms.",
    "Use English-language political blogs to learn about governance.",
    "Tip: Practice your listening by watching English gaming streams.",
    "Don't be afraid to ask for feedback on your writing.",
    "Tip: Learn how to use 'correlative conjunctions' like either/or.",
    "Read English poetry to improve your sense of rhythm.",
    "Tip: Use English-language apps for news and current events.",
    "Practice your English by describing a person you admire.",
    "Tip: Learn the names of common environmental terms.",
    "Use English-language space blogs to learn about the cosmos.",
    "Tip: Practice your listening by watching English cooking shows.",
    "Don't be afraid to use English to express your feelings.",
    "Tip: Learn how to use 'participle clauses' for efficiency.",
    "Read English thrillers to stay on the edge of your seat.",
    "Tip: Use English-language apps for social networking.",
    "Practice your English by writing a script for a short play.",
    "Tip: Learn the names of common economic terms.",
    "Use English-language psychology blogs to learn about the mind.",
    "Tip: Practice your listening by watching English fashion shows.",
    "Don't be afraid to use English in your professional life.",
    "Tip: Learn how to use 'prepositional phrases' for detail.",
    "Read English memoirs to learn about personal experiences.",
    "Tip: Use English-language apps for photography and editing.",
    "Practice your English by describing a movie plot.",
    "Tip: Learn the names of common sociological terms.",
    "Use English-language education blogs to learn about learning.",
    "Tip: Practice your listening by watching English tech reviews.",
    "Don't be afraid to use English to make new friends.",
    "Tip: Learn how to use 'adverbial clauses' for more context.",
    "Read English essays to see how arguments are structured.",
    "Tip: Use English-language apps for productivity and organization.",
    "Practice your English by writing a blog post about your day.",
    "Tip: Learn the names of common mythological figures.",
    "Use English-language architecture blogs to learn about buildings.",
    "Tip: Practice your listening by watching English travel vlogs.",
    "Don't be afraid to use English to explore new cultures.",
    "Tip: Learn how to use 'noun clauses' as subjects or objects.",
    "Read English folklore to learn about different traditions.",
    "Tip: Use English-language apps for entertainment and fun.",
    "Practice your English by describing a historical event.",
    "Tip: Learn the names of common linguistic terms.",
    "Use English-language biology blogs to learn about life.",
    "Tip: Practice your listening by watching English music videos.",
    "Don't be afraid to use English to pursue your passions.",
    "Tip: Learn how to use 'cleft sentences' for emphasis.",
    "Read English plays to see how dialogue is written.",
    "Tip: Use English-language apps for shopping and deals.",
    "Practice your English by writing a letter to an editor.",
    "Tip: Learn the names of common chemical elements.",
    "Use English-language physics blogs to learn about the universe.",
    "Tip: Practice your listening by watching English movie reviews.",
    "Don't be afraid to use English to advocate for yourself.",
    "Tip: Learn how to use 'inversion' for formal emphasis.",
    "Read English letters to see how personal news is shared.",
    "Tip: Use English-language apps for health and fitness.",
    "Practice your English by describing a scientific process.",
    "Tip: Learn the names of common anatomical terms.",
    "Use English-language archaeology blogs to learn about the past.",
    "Tip: Practice your listening by watching English documentary series.",
    "Don't be afraid to use English to learn something new.",
    "Tip: Learn how to use 'fronting' to shift focus in a sentence.",
    "Read English speeches to see how to inspire others.",
    "Tip: Use English-language apps for finance and investment.",
    "Practice your English by writing a business proposal.",
    "Tip: Learn the names of common astronomical phenomena.",
    "Use English-language environment blogs to learn about nature.",
    "Tip: Practice your listening by watching English award ceremonies.",
    "Don't be afraid to use English to share your ideas.",
    "Tip: Learn how to use 'ellipsis' for more concise speech.",
    "Read English satire to see how humor is used.",
    "Tip: Use English-language apps for creativity and art.",
    "Practice your English by describing a work of art.",
    "Tip: Learn the names of common medical conditions.",
    "Use English-language technology blogs to learn about software.",
    "Tip: Practice your listening by watching English interview series.",
    "Don't be afraid to use English to tell a joke.",
    "Tip: Learn how to use 'substitution' to avoid repetition.",
    "Read English myths to learn about ancient stories.",
    "Tip: Use English-language apps for productivity and time management.",
    "Practice your English by writing a product description.",
    "Tip: Learn the names of common geological periods.",
    "Use English-language philosophy blogs to learn about thought.",
    "Tip: Practice your listening by watching English panel shows.",
    "Don't be afraid to use English to ask for directions.",
    "Tip: Learn how to use 'nominalization' for formal writing.",
    "Read English legends to learn about heroic tales.",
    "Tip: Use English-language apps for language learning and practice.",
    "Practice your English by describing a complex problem.",
    "Tip: Learn the names of common psychological disorders.",
    "Use English-language sociology blogs to learn about society.",
    "Tip: Practice your listening by watching English street interviews.",
    "Don't be afraid to use English to give a presentation.",
    "Tip: Learn how to use 'parallel structure' for clearer writing.",
    "Read English fables to learn about moral lessons.",
    "Tip: Use English-language apps for travel and exploration.",
    "Practice your English by writing a cover letter.",
    "Tip: Learn the names of common legal procedures.",
    "Use English-language law blogs to learn about justice.",
    "Tip: Practice your listening by watching English legal dramas.",
    "Don't be afraid to use English to negotiate.",
    "Tip: Learn how to use 'hedging' to sound less direct.",
    "Read English journals to see how research is shared.",
    "Tip: Use English-language apps for cooking and nutrition.",
    "Practice your English by describing a future goal.",
    "Tip: Learn the names of common engineering terms.",
    "Use English-language engineering blogs to learn about building.",
    "Tip: Practice your listening by watching English science shows.",
    "Don't be afraid to use English to apologize.",
    "Tip: Learn how to use 'intensifying adverbs' for impact.",
    "Read English brochures to learn about products and services.",
    "Tip: Use English-language apps for mindfulness and focus.",
    "Practice your English by writing a short biography.",
    "Tip: Learn the names of common economic indicators.",
    "Use English-language business blogs to learn about markets.",
    "Tip: Practice your listening by watching English business news.",
    "Don't be afraid to use English to compliment someone.",
    "Tip: Learn how to use 'phrasal verbs' with multiple meanings.",
    "Read English manuals to learn how things work.",
    "Tip: Use English-language apps for news and information.",
    "Practice your English by describing a cultural tradition.",
    "Tip: Learn the names of common environmental issues.",
    "Use English-language conservation blogs to learn about nature.",
    "Tip: Practice your listening by watching English nature films.",
    "Don't be afraid to use English to express an opinion.",
    "Tip: Learn how to use 'discourse markers' to organize speech.",
    "Read English reports to see how data is presented.",
    "Tip: Use English-language apps for entertainment and media.",
    "Practice your English by writing a summary of a movie.",
    "Tip: Learn the names of common medical treatments.",
    "Use English-language health blogs to learn about wellness.",
    "Tip: Practice your listening by watching English health shows.",
    "Don't be afraid to use English to ask for advice.",
    "Tip: Learn how to use 'idiomatic expressions' in context.",
    "Read English newspapers to stay updated on global news.",
    "Tip: Use English-language apps for social connection.",
    "Practice your English by describing a personal achievement.",
    "Tip: Learn the names of common scientific instruments.",
    "Use English-language laboratory blogs to learn about research.",
    "Tip: Practice your listening by watching English lab demos.",
    "Don't be afraid to use English to solve a problem.",
    "Tip: Learn how to use 'complex prepositions' like in spite of.",
    "Read English textbooks to learn academic subjects.",
    "Tip: Use English-language apps for learning and growth.",
    "Practice your English by writing a letter to a friend.",
    "Tip: Learn the names of common artistic techniques.",
    "Use English-language design blogs to learn about aesthetics.",
    "Tip: Practice your listening by watching English design shows.",
    "Don't be afraid to use English to make a complaint.",
    "Tip: Learn how to use 'modal verbs of obligation' like must/should.",
    "Read English magazines for lifestyle and fashion tips.",
    "Tip: Use English-language apps for shopping and lifestyle.",
    "Practice your English by describing a dream you had.",
    "Tip: Learn the names of common business roles.",
    "Use English-language management blogs to learn about leadership.",
    "Tip: Practice your listening by watching English leadership talks.",
    "Don't be afraid to use English to lead a discussion.",
    "Tip: Learn how to use 'reflexive pronouns' correctly.",
    "Read English websites for travel and leisure ideas.",
    "Tip: Use English-language apps for leisure and fun.",
    "Practice your English by writing a short story about an adventure.",
    "Tip: Learn the names of common technological terms.",
    "Use English-language innovation blogs to learn about the future.",
    "Tip: Practice your listening by watching English innovation talks.",
    "Don't be afraid to use English to innovate and create.",
    "Tip: Learn how to use 'conjunctions of time' like while/as.",
    "Read English encyclopedias to learn a wide range of facts.",
    "Tip: Use English-language apps for knowledge and learning.",
    "Practice your English by describing a famous person.",
    "Tip: Learn the names of common historical periods.",
    "Use English-language history blogs to learn about civilization.",
    "Tip: Practice your listening by watching English history shows.",
    "Don't be afraid to use English to debate a topic.",
    "Tip: Learn how to use 'comparative adverbs' for detail.",
    "Read English novels for deep immersion in stories.",
    "Tip: Use English-language apps for storytelling and reading.",
    "Practice your English by writing a poem about nature.",
    "Tip: Learn the names of common natural phenomena.",
    "Use English-language ecology blogs to learn about the world.",
    "Tip: Practice your listening by watching English ecology shows.",
    "Don't be afraid to use English to stand up for something.",
    "Tip: Learn how to use 'auxiliary verbs' for emphasis.",
    "Read English scripts to see how characters interact.",
    "Tip: Use English-language apps for theater and performance.",
    "Practice your English by describing a stage play.",
    "Tip: Learn the names of common theater terms.",
    "Use English-language drama blogs to learn about acting.",
    "Tip: Practice your listening by watching English theater clips.",
    "Don't be afraid to use English to perform and express.",
    "Tip: Learn how to use 'negative inversion' for formal style.",
    "Read English non-fiction for insights into the real world.",
    "Tip: Use English-language apps for real-world learning.",
    "Practice your English by writing an article about a hobby.",
    "Tip: Learn the names of common hobby-related terms.",
    "Use English-language interest blogs to learn about passions.",
    "Tip: Practice your listening by watching English hobby videos.",
    "Don't be afraid to use English to share your passions.",
    "Tip: Learn how to use 'prepositions of place' accurately.",
    "Read English travelogues for inspiration for your next trip.",
    "Tip: Use English-language apps for trip planning.",
    "Practice your English by describing a place you want to visit.",
    "Tip: Learn the names of common travel-related terms.",
    "Use English-language tourism blogs to learn about destinations.",
    "Tip: Practice your listening by watching English travel shows.",
    "Don't be afraid to use English to explore the world.",
    "Tip: Learn how to use 'relative pronouns' for clarity.",
    "Read English guides for practical tips and advice.",
    "Tip: Use English-language apps for practical living.",
    "Practice your English by writing a 'how-to' guide.",
    "Tip: Learn the names of common 'how-to' terms.",
    "Use English-language advice blogs to learn about life skills.",
    "Tip: Practice your listening by watching English advice videos.",
    "Don't be afraid to use English to help others.",
    "Tip: Learn how to use 'sentence connectors' for logic.",
    "Read English opinion pieces to see different viewpoints.",
    "Tip: Use English-language apps for opinion and debate.",
    "Practice your English by writing an argumentative essay.",
    "Tip: Learn the names of common debate terms.",
    "Use English-language forum blogs to learn about discussions.",
    "Tip: Practice your listening by watching English debate series.",
    "Don't be afraid to use English to state your case.",
    "Tip: Learn how to use 'modal verbs of ability' like can/could.",
    "Read English success stories for motivation and ideas.",
    "Tip: Use English-language apps for success and goal-setting.",
    "Practice your English by describing a success you've had.",
    "Tip: Learn the names of common success-related terms.",
    "Use English-language motivation blogs to learn about achievement.",
    "Tip: Practice your listening by watching English motivation talks.",
    "Don't be afraid to use English to achieve your goals.",
    "Tip: Learn how to use 'indefinite pronouns' like anyone/everyone.",
    "Read English letters to the editor for community viewpoints.",
    "Tip: Use English-language apps for community engagement.",
    "Practice your English by writing a letter to your local paper.",
    "Tip: Learn the names of common community-related terms.",
    "Use English-language local blogs to learn about your area.",
    "Tip: Practice your listening by watching English local news.",
    "Don't be afraid to use English to engage with your community.",
    "Tip: Learn how to use 'stative verbs' vs 'dynamic verbs'.",
    "Read English research papers for in-depth knowledge.",
    "Tip: Use English-language apps for research and study.",
    "Practice your English by writing a summary of a study.",
    "Tip: Learn the names of common research-related terms.",
    "Use English-language academic blogs to learn about studies.",
    "Tip: Practice your listening by watching English research talks.",
    "Don't be afraid to use English to explore deep topics.",
    "Tip: Learn how to use 'conjunctions of cause and effect'.",
    "Read English analyses to see how things are evaluated.",
    "Tip: Use English-language apps for analysis and logic.",
    "Practice your English by writing an analysis of a book.",
    "Tip: Learn the names of common analytical terms.",
    "Use English-language logic blogs to learn about reasoning.",
    "Tip: Practice your listening by watching English logic videos.",
    "Don't be afraid to use English to think critically.",
    "Tip: Learn how to use 'prepositions of time' like in/on/at.",
    "Read English schedules to manage your time effectively.",
    "Tip: Use English-language apps for time and scheduling.",
    "Practice your English by writing your weekly schedule.",
    "Tip: Learn the names of common time-related terms.",
    "Use English-language productivity blogs to learn about time.",
    "Tip: Practice your listening by watching English time management videos.",
    "Don't be afraid to use English to organize your life.",
    "Tip: Learn how to use 'demonstrative pronouns' like this/that.",
    "Read English descriptions to see how things are pointed out.",
    "Tip: Use English-language apps for description and detail.",
    "Practice your English by describing an object in your room.",
    "Tip: Learn the names of common object-related terms.",
    "Use English-language catalog blogs to learn about items.",
    "Tip: Practice your listening by watching English product reviews.",
    "Don't be afraid to use English to describe the world.",
    "Tip: Learn how to use 'interrogative pronouns' for questions.",
    "Read English FAQs for answers to common questions.",
    "Tip: Use English-language apps for questions and answers.",
    "Practice your English by writing a list of questions.",
    "Tip: Learn the names of common question-related terms.",
    "Use English-language Q&A blogs to learn about inquiries.",
    "Tip: Practice your listening by watching English Q&A sessions.",
    "Don't be afraid to use English to ask anything.",
    "Tip: Learn how to use 'possessive pronouns' like mine/yours.",
    "Read English ownership documents for formal language.",
    "Tip: Use English-language apps for ownership and rights.",
    "Practice your English by writing about things you own.",
    "Tip: Learn the names of common possession-related terms.",
    "Use English-language property blogs to learn about ownership.",
    "Tip: Practice your listening by watching English property shows.",
    "Don't be afraid to use English to talk about what's yours.",
    "Tip: Learn how to use 'personal pronouns' accurately.",
    "Read English biographies for personal stories.",
    "Tip: Use English-language apps for personal development.",
    "Practice your English by writing your own biography.",
    "Tip: Learn the names of common personal-related terms.",
    "Use English-language personal blogs to learn about lives.",
    "Tip: Practice your listening by watching English personal vlogs.",
    "Don't be afraid to use English to be yourself.",
    "Tip: Learn how to use 'adjectives' to add color to your speech.",
    "Read English descriptions of nature for beautiful language.",
    "Tip: Use English-language apps for art and beauty.",
    "Practice your English by writing a description of a sunset.",
    "Tip: Learn the names of common color and light terms.",
    "Use English-language art blogs to learn about visuals.",
    "Tip: Practice your listening by watching English art videos.",
    "Don't be afraid to use English to see the beauty.",
    "Tip: Learn how to use 'adverbs' to describe actions.",
    "Read English action stories for fast-paced language.",
    "Tip: Use English-language apps for action and excitement.",
    "Practice your English by writing about an exciting event.",
    "Tip: Learn the names of common action-related terms.",
    "Use English-language adventure blogs to learn about action.",
    "Tip: Practice your listening by watching English action movies.",
    "Don't be afraid to use English to live an adventure.",
    "Tip: Keep your learning consistent, even if it's just 10 minutes.",
    "Tip: Language learning is a marathon, not a sprint—take your time.",
    "Tip: Try to find a 'study buddy' to keep each other motivated.",
    "Tip: Use your mistakes as stepping stones to better understanding.",
    "Tip: Immerse yourself in English as much as possible daily.",
    "Tip: Be patient with yourself; fluency takes time and effort.",
    "Tip: Enjoy the journey of learning a new language!",
    "Tip: Every word you learn brings you closer to your goal.",
    "Tip: Stay curious and never stop asking questions about English.",
    "Tip: You've got this—keep practicing and you will succeed!",
];

export default function LoadingOverlay({ show }: LoadingOverlayProps) {
    const { enableScroll, disableScroll } = useBodyScroll();

    const randomTip = useMemo(() => {
        if (!show) return "";
        // eslint-disable-next-line react-hooks/purity
        return tips[Math.floor(Math.random() * tips.length)];
    }, [show]);

    useEffect(() => {
        if (show) {
            disableScroll();
        } else {
            enableScroll();
        }
        return () => {
            enableScroll();
        };
    }, [show, enableScroll, disableScroll]);

    return (
        <AnimatePresence mode="wait">
            {show && (
                <motion.div
                    className="fixed top-0 left-0 w-full h-full bg-surface z-100 flex flex-col gap-3
                    items-center justify-center p-6 text-center"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                >
                    <OrbitProgress dense size="medium" color="#32b5c7" />
                    <div className="flex flex-col gap-2 items-center">
                        <p className="text-xl sm:text-2xl font-medium text-primary">
                            Loading...
                        </p>
                        <p className="text-sm sm:text-base text-secondary max-w-xs leading-relaxed">
                            {randomTip}
                        </p>
                    </div>
                </motion.div>
            )}
        </AnimatePresence>
    );
}
